let usuarioLogado=null,materias=[],trabalhos=[],trabalhoEmEdicao=null,visao='lista',referencia=new Date();
const $=id=>document.getElementById(id);
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const isoLocal=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const hojeISO=()=>isoLocal(new Date());
const fmt=iso=>iso?new Date(iso+'T12:00:00').toLocaleDateString('pt-BR'):'';
const inicioSemana=d=>{const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-((x.getDay()+6)%7));return x};

async function iniciar(){usuarioLogado=await protegerPagina();if(!usuarioLogado)return;preparar();await carregarMaterias();await carregarTrabalhos();}
function preparar(){
 const filtros=document.querySelector('.trabalhos-filtros');if(filtros)filtros.innerHTML='<button type="button" class="filtro-trabalho ativo" data-view="lista">Lista</button><button type="button" class="filtro-trabalho" data-view="semana">Semana</button><button type="button" class="filtro-trabalho" data-view="mes">Mês</button>';
 document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{visao=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('ativo',x===b));render()});
 $('novaTrabalho')?.addEventListener('click',abrirNovo);$('criarPrimeiraTrabalho')?.addEventListener('click',abrirNovo);$('fecharModalTrabalho')?.addEventListener('click',fechar);$('cancelarTrabalho')?.addEventListener('click',fechar);$('modalTrabalho')?.addEventListener('click',e=>{if(e.target===$('modalTrabalho'))fechar()});$('formTrabalho')?.addEventListener('submit',salvar);
 const label=document.querySelector('label[for="nomeTrabalho"]');if(label)label.textContent='Nome do trabalho';const ph=$('nomeTrabalho');if(ph)ph.placeholder='Ex.: Trabalho de Química';
}
async function carregarMaterias(){const {data,error}=await nexoSupabase.from('materias').select('id,nome').eq('usuario_id',usuarioLogado.id).order('nome');if(error){console.error(error);return}materias=data||[];const s=$('materiaTrabalho');if(s)s.innerHTML='<option value="">Sem matéria</option>'+materias.map(m=>`<option value="${m.id}">${esc(m.nome)}</option>`).join('')}
async function carregarTrabalhos(){const {data,error}=await nexoSupabase.from('trabalhos').select('id,nome,descricao,data,horario,materia_id,materia_nome,no_calendario,concluido,visibilidade,criado_em').eq('usuario_id',usuarioLogado.id).eq('visibilidade','privada').order('data').order('horario');if(error){console.error(error);alert('Não foi possível carregar os trabalhos: '+error.message);return}trabalhos=data||[];resumo();render()}
function materiaNome(t){return t.materia_nome||materias.find(m=>m.id===t.materia_id)?.nome||'Sem matéria'}
function resumo(){const h=hojeISO();if($('totalProximas'))$('totalProximas').textContent=trabalhos.filter(t=>t.data>h&&!t.concluido).length;if($('totalHoje'))$('totalHoje').textContent=trabalhos.filter(t=>t.data===h&&!t.concluido).length;if($('totalRealizadas'))$('totalRealizadas').textContent=trabalhos.filter(t=>t.concluido||t.data<h).length}
function render(){if(visao==='semana')renderSemana();else if(visao==='mes')renderMes();else renderLista()}
function cardLista(t){return `<article class="atividade-card ${t.concluido?'concluida':''}" data-id="${t.id}"><button type="button" class="atividade-check" data-act="toggle" aria-label="${t.concluido?'Reabrir':'Concluir'} trabalho">${t.concluido?'✓':''}</button><div class="atividade-conteudo"><div class="atividade-topo"><h3>${esc(t.nome)}</h3><span class="atividade-materia">${esc(materiaNome(t))}</span></div><div class="atividade-meta"><span>${fmt(t.data)}</span>${t.horario?`<span>${t.horario.slice(0,5)}</span>`:''}</div>${t.descricao?`<p class="atividade-descricao">${esc(t.descricao)}</p>`:''}</div><div class="atividade-acoes"><button type="button" class="atividade-editar" data-act="edit">Editar</button><button type="button" class="atividade-excluir" data-act="del">Excluir</button></div></article>`}
function bind(){document.querySelectorAll('#listaTrabalhosPagina [data-id]').forEach(el=>el.addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(!b)return;const id=el.dataset.id;if(b.dataset.act==='toggle')alternar(id);if(b.dataset.act==='edit')editar(id);if(b.dataset.act==='del')excluir(id)}))}
function renderLista(){const box=$('listaTrabalhosPagina');if(!box)return;box.className='atividades-lista';box.innerHTML=trabalhos.length?trabalhos.map(cardLista).join(''):'<div class="estado-vazio"><div class="vazio-icone">✎</div><h3>Nenhum trabalho</h3><p>Você ainda não cadastrou nenhum trabalho.</p><button type="button" class="botao-vazio" id="novoVazio">+ Adicionar trabalho</button></div>';$('novoVazio')?.addEventListener('click',abrirNovo);bind()}
function itemSemana(t){const el=document.createElement('div');el.className='semana-item semana-item-trabalho';el.innerHTML=`<span class="semana-item-tipo">TRABALHO</span><strong>${esc(t.nome)}</strong><span class="semana-item-materia">${esc(materiaNome(t))}</span>${t.horario?`<span class="semana-item-horario">${t.horario.slice(0,5)}</span>`:''}`;el.onclick=()=>editar(t.id);return el}
function renderSemana(){const box=$('listaTrabalhosPagina');if(!box)return;box.className='estudos-calendario-wrap';const ini=inicioSemana(referencia),fim=new Date(ini);fim.setDate(fim.getDate()+6);box.innerHTML=`<div class="estudo-cal-nav"><button id="trabAnt">‹</button><div><strong>Minha semana</strong><span>${fmt(isoLocal(ini))} até ${fmt(isoLocal(fim))}</span></div><button id="trabProx">›</button></div><div class="semana-legenda"><span><i class="legenda-trabalho"></i>Trabalho</span></div><section class="semana-grade" id="trabalhoSemanaGrade"></section>`;const grade=$('trabalhoSemanaGrade'),nomes=['Segunda','Terça','Quarta','Quinta','Sexta','Sábado','Domingo'],hoje=hojeISO();for(let i=0;i<7;i++){const d=new Date(ini);d.setDate(ini.getDate()+i);const iso=isoLocal(d),arr=trabalhos.filter(t=>t.data===iso&&!t.concluido).sort((a,b)=>(a.horario||'99:99').localeCompare(b.horario||'99:99'));const col=document.createElement('article');col.className='semana-dia'+(iso===hoje?' semana-dia-hoje':'');col.innerHTML=`<div class="semana-dia-cabecalho"><div><span class="semana-dia-nome">${nomes[i]}</span><strong class="semana-dia-numero">${d.getDate()}</strong></div><button class="semana-adicionar" type="button">+</button></div><div class="semana-itens"></div>`;col.querySelector('.semana-adicionar').onclick=()=>abrirNaData(iso);const area=col.querySelector('.semana-itens');if(!arr.length)area.innerHTML='<div class="semana-dia-vazio">Nenhum item</div>';else arr.forEach(t=>area.appendChild(itemSemana(t)));grade.appendChild(col)}$('trabAnt').onclick=()=>{referencia.setDate(referencia.getDate()-7);renderSemana()};$('trabProx').onclick=()=>{referencia.setDate(referencia.getDate()+7);renderSemana()}}
function renderMes(){const box=$('listaTrabalhosPagina');if(!box)return;box.className='estudos-calendario-wrap';const y=referencia.getFullYear(),m=referencia.getMonth(),first=new Date(y,m,1),start=(first.getDay()+6)%7,base=new Date(y,m,1-start),hoje=hojeISO(),titulo=referencia.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});box.innerHTML=`<div class="estudo-cal-nav"><button id="trabAnt">‹</button><div><strong>${titulo.charAt(0).toUpperCase()+titulo.slice(1)}</strong></div><button id="trabProx">›</button></div><div class="mes-legenda"><span><i class="legenda-trabalho"></i>Trabalho</span></div><section class="calendario-mes"><div class="calendario-semana-nomes"><span>SEG</span><span>TER</span><span>QUA</span><span>QUI</span><span>SEX</span><span>SÁB</span><span>DOM</span></div><div class="calendario-grade" id="trabalhoMesGrade"></div></section>`;const grade=$('trabalhoMesGrade');for(let i=0;i<42;i++){const d=new Date(base);d.setDate(base.getDate()+i);const iso=isoLocal(d),arr=trabalhos.filter(t=>t.data===iso&&!t.concluido).sort((a,b)=>(a.horario||'99:99').localeCompare(b.horario||'99:99'));const cell=document.createElement('article');cell.className='calendario-dia'+(d.getMonth()!==m?' calendario-outro-mes':'')+(iso===hoje?' calendario-hoje':'');cell.innerHTML=`<div class="calendario-dia-topo"><span class="calendario-numero">${d.getDate()}</span><button type="button" class="calendario-adicionar">+</button></div><div class="calendario-itens"></div>`;cell.querySelector('.calendario-adicionar').onclick=e=>{e.stopPropagation();abrirNaData(iso)};const area=cell.querySelector('.calendario-itens');arr.slice(0,3).forEach(t=>{const item=document.createElement('div');item.className='calendario-item calendario-item-trabalho';item.innerHTML=`<strong>${esc(t.nome)}</strong><span>${t.horario?t.horario.slice(0,5)+' • ':''}${esc(materiaNome(t))}</span>`;item.onclick=e=>{e.stopPropagation();editar(t.id)};area.appendChild(item)});if(arr.length>3){const more=document.createElement('span');more.className='calendario-mais';more.textContent=`+${arr.length-3} itens`;area.appendChild(more)}grade.appendChild(cell)}$('trabAnt').onclick=()=>{referencia=new Date(y,m-1,1);renderMes()};$('trabProx').onclick=()=>{referencia=new Date(y,m+1,1);renderMes()}}
function abrirNovo(){trabalhoEmEdicao=null;$('formTrabalho')?.reset();if($('tituloModalTrabalho'))$('tituloModalTrabalho').textContent='Novo trabalho';$('modalTrabalho')?.classList.add('ativo')}
function abrirNaData(data){abrirNovo();if($('dataTrabalho'))$('dataTrabalho').value=data}
function fechar(){$('modalTrabalho')?.classList.remove('ativo')}
function editar(id){const t=trabalhos.find(x=>x.id===id);if(!t)return;trabalhoEmEdicao=id;$('nomeTrabalho').value=t.nome||'';$('materiaTrabalho').value=t.materia_id||'';$('dataTrabalho').value=t.data||'';$('horarioTrabalho').value=t.horario?.slice(0,5)||'';const desc=$('conteudoTrabalho')||$('descricaoTrabalho');if(desc)desc.value=t.descricao||'';if($('tituloModalTrabalho'))$('tituloModalTrabalho').textContent='Editar trabalho';$('modalTrabalho')?.classList.add('ativo')}
async function salvar(e){e.preventDefault();if(!usuarioLogado)return;const nome=$('nomeTrabalho').value.trim(),materia_id=$('materiaTrabalho').value||null,data=$('dataTrabalho').value,horario=$('horarioTrabalho').value||null,descEl=$('conteudoTrabalho')||$('descricaoTrabalho'),descricao=descEl?.value.trim()||null;if(!nome||!data){alert('Informe o nome e a data do trabalho.');return}const payload={nome,descricao,data,horario,materia_id,materia_nome:materias.find(m=>m.id===materia_id)?.nome||null,usuario_id:usuarioLogado.id,visibilidade:'privada',no_calendario:true};let q=trabalhoEmEdicao?nexoSupabase.from('trabalhos').update(payload).eq('id',trabalhoEmEdicao).eq('usuario_id',usuarioLogado.id):nexoSupabase.from('trabalhos').insert(payload);const {error}=await q;if(error){console.error(error);alert('Não foi possível salvar o trabalho: '+error.message);return}fechar();await carregarTrabalhos()}
async function alternar(id){const t=trabalhos.find(x=>x.id===id);if(!t)return;const {error}=await nexoSupabase.from('trabalhos').update({concluido:!t.concluido}).eq('id',id).eq('usuario_id',usuarioLogado.id);if(error){alert(error.message);return}await carregarTrabalhos()}
async function excluir(id){if(!confirm('Excluir este trabalho?'))return;const {error}=await nexoSupabase.from('trabalhos').delete().eq('id',id).eq('usuario_id',usuarioLogado.id);if(error){alert(error.message);return}await carregarTrabalhos()}
document.addEventListener('DOMContentLoaded',iniciar);
